/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Helpers for writing pickle payloads by hand in tests.
 *
 * CPython's pickler cannot emit a malformed payload, so the cases that pin how
 * a reader rejects one have to be assembled byte by byte.
 */

/** Opcode byte for `STOP`, which every payload ends with. */
export const STOP = 0x2e;

/** Builds a payload from opcode bytes, ASCII runs and byte arrays. */
export function payload(
  ...parts: Array<number | string | Uint8Array>
): Uint8Array {
  const bytes: number[] = [];
  for (const part of parts) {
    if (typeof part === 'number') {
      bytes.push(part);
    } else if (typeof part === 'string') {
      bytes.push(...new TextEncoder().encode(part));
    } else {
      bytes.push(...part);
    }
  }
  return Uint8Array.from(bytes);
}

/** Little-endian unsigned 32-bit length prefix. */
export function le32(value: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, value, true);
  return out;
}

/** Little-endian unsigned 64-bit length prefix. */
export function le64(value: number): Uint8Array {
  const out = new Uint8Array(8);
  new DataView(out.buffer).setBigUint64(0, BigInt(value), true);
  return out;
}

/** Big-endian IEEE-754 double, as `BINFLOAT` stores it. */
export function be64f(value: number): Uint8Array {
  const out = new Uint8Array(8);
  new DataView(out.buffer).setFloat64(0, value, false);
  return out;
}

/** Decodes a base64 fixture generated by CPython's `pickle.dumps`. */
export function fromBase64(text: string): Uint8Array {
  return Uint8Array.from(Buffer.from(text, 'base64'));
}
