/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  BaseLlm,
  BaseLlmConnection,
  Event,
  FunctionTool,
  InMemoryRunner,
  LlmAgent,
  LlmRequest,
  LlmResponse,
  RestApiTool,
} from '@google/adk';
import {createUserContent, Part} from '@google/genai';
import * as http from 'http';
import {OpenAPIV3} from 'openapi-types';
import {afterAll, beforeAll, describe, expect, it} from 'vitest';
import {z} from 'zod';

class ManualTestLlm extends BaseLlm {
  responses: LlmResponse[] = [];
  callCount = 0;

  constructor(responses: LlmResponse[]) {
    super({model: 'manual-e2e-llm'});
    this.responses = responses;
  }

  async *generateContentAsync(
    _request: LlmRequest,
  ): AsyncGenerator<LlmResponse, void, void> {
    const response = this.responses[this.callCount];
    this.callCount++;
    if (response) {
      yield response;
    }
  }

  async connect(_llmRequest: LlmRequest): Promise<BaseLlmConnection> {
    throw new Error('Method not implemented.');
  }
}

describe('Manual E2E Test: LlmAgent with long-running and authenticated tools', () => {
  let server: http.Server;
  let port: number;

  beforeAll(() => {
    server = http.createServer((req, res) => {
      if (req.headers['x-api-key'] === 'valid-secret-key') {
        res.writeHead(200, {'Content-Type': 'application/json'});
        res.end(JSON.stringify({status: 'authenticated_success'}));
      } else {
        res.writeHead(401);
        res.end('Unauthorized');
      }
    });
    return new Promise<void>((resolve) => {
      server.listen(0, () => {
        const address = server.address();
        if (address && typeof address !== 'string') {
          port = address.port;
        }
        resolve();
      });
    });
  });

  afterAll(() => {
    return new Promise<void>((resolve) => {
      server.close(() => resolve());
    });
  });

  it('should detect longRunningToolIds and generate adk_request_credential events during execution', async () => {
    const longRunningTool = new FunctionTool({
      name: 'long_processing_tool',
      description: 'A tool that runs for a long time',
      parameters: z.object({data: z.string()}),
      isLongRunning: true,
      execute: async ({data}) => {
        return {result: `Processed ${data}`};
      },
    });

    const endpoint = {
      baseUrl: `http://localhost:${port}`,
      path: '/data',
      method: 'GET',
    };
    const operation: OpenAPIV3.OperationObject = {
      responses: {
        '200': {
          description: 'Success',
          content: {
            'application/json': {
              schema: {type: 'object'},
            },
          },
        },
      },
    };
    const authScheme: OpenAPIV3.SecuritySchemeObject = {
      type: 'apiKey',
      name: 'X-API-Key',
      in: 'header',
    };

    const authTool = new RestApiTool(
      'secure_api_tool',
      'A tool requiring auth',
      endpoint,
      operation,
      authScheme,
    );

    const manualLlm = new ManualTestLlm([
      // Step 1: LLM returns function calls for both the long-running tool and the auth tool
      {
        content: {
          role: 'model',
          parts: [
            {
              functionCall: {
                name: 'long_processing_tool',
                args: {data: 'payload_1'},
              },
            },
            {
              functionCall: {
                name: 'secure_api_tool',
                args: {},
              },
            },
          ],
        },
      },
      // Step 2: After credentials are provided and tool runs, LLM returns final answer
      {
        content: {
          role: 'model',
          parts: [{text: 'All tools executed successfully!'}],
        },
      },
    ]);

    const agent = new LlmAgent({
      name: 'manual_e2e_agent',
      model: manualLlm,
      tools: [longRunningTool, authTool],
    });

    const runner = new InMemoryRunner({
      agent,
      appName: 'ManualE2EApp',
    });

    const session = await runner.sessionService.createSession({
      appName: 'ManualE2EApp',
      userId: 'test-user',
    });

    const events: Event[] = [];
    for await (const event of runner.runAsync({
      userId: 'test-user',
      sessionId: session.id,
      newMessage: createUserContent('Execute both tools'),
    })) {
      events.push(event);
    }

    // Verify longRunningToolIds on the model event containing function calls
    const modelCallEvent = events.find(
      (e) =>
        e.author === 'manual_e2e_agent' &&
        (e.longRunningToolIds?.length ?? 0) > 0,
    );
    expect(modelCallEvent).toBeDefined();
    expect(modelCallEvent!.longRunningToolIds!.length).toBeGreaterThan(0);

    // Verify adk_request_credential event was generated by internalized generateAuthEvent
    const authEvent = events.find((e) =>
      e.content?.parts?.some(
        (p: Part) => p.functionCall?.name === 'adk_request_credential',
      ),
    );
    expect(authEvent).toBeDefined();
    expect(authEvent!.author).toBe('manual_e2e_agent');
  });
});
