/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {Content, createPartFromText} from '@google/genai';
import {context, trace} from '@opentelemetry/api';

import {BaseAgent} from '../agents/base_agent.js';
import {
  InvocationContext,
  newInvocationContextId,
} from '../agents/invocation_context.js';
import {isLlmAgent} from '../agents/llm_agent.js';
import {createRunConfig, RunConfig} from '../agents/run_config.js';
import {BaseArtifactService} from '../artifacts/base_artifact_service.js';
import {ScopedArtifactService} from '../artifacts/scoped_artifact_service.js';

import {BaseCredentialService} from '../auth/credential_service/base_credential_service.js';
import {
  BuiltInCodeExecutor,
  isBuiltInCodeExecutor,
} from '../code_executors/built_in_code_executor.js';
import {createEvent, Event, getFunctionCalls} from '../events/event.js';
import {createEventActions} from '../events/event_actions.js';
import {BaseMemoryService} from '../memory/base_memory_service.js';
import {BasePlugin} from '../plugins/base_plugin.js';
import {PluginManager} from '../plugins/plugin_manager.js';
import {BaseSessionService} from '../sessions/base_session_service.js';
import {Session} from '../sessions/session.js';
import {
  runAsyncGeneratorWithOtelContext,
  tracer,
} from '../telemetry/tracing.js';
import {BaseToolset, isBaseToolset} from '../tools/base_toolset.js';
import {logger} from '../utils/logger.js';
import {isGemini2OrAbove} from '../utils/model_name.js';

/**
 * The configuration parameters for the Runner.
 */
export interface RunnerConfig {
  /**
   * The application name.
   */
  appName: string;

  /**
   * The agent to run.
   */
  agent: BaseAgent;

  /**
   * An optional list of plugins to apply globally across all agents.
   */
  plugins?: BasePlugin[];

  /**
   * An optional service for storing and retrieving artifacts.
   */
  artifactService?: BaseArtifactService;

  /**
   * The service for managing sessions.
   */
  sessionService: BaseSessionService;

  /**
   * An optional service for storing and querying agent memory.
   */
  memoryService?: BaseMemoryService;

  /**
   * An optional service for managing authentication credentials.
   */
  credentialService?: BaseCredentialService;
}

/**
 * A unique symbol to identify ADK agent classes.
 * Defined once and shared by all Runner instances.
 */
const RUNNER_SIGNATURE_SYMBOL = Symbol.for('google.adk.runner');

/**
 * Type guard to check if an object is an instance of Runner.
 * @param obj The object to check.
 * @returns True if the object is an instance of Runner, false otherwise.
 */
export function isRunner(obj: unknown): obj is Runner {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    RUNNER_SIGNATURE_SYMBOL in obj &&
    obj[RUNNER_SIGNATURE_SYMBOL] === true
  );
}

/**
 * Orchestrates agent execution for a given application.
 *
 * The Runner manages the full lifecycle of an agent invocation: it loads the
 * session, invokes plugin callbacks, runs the root agent, and yields the
 * resulting events. Use {@link InMemoryRunner} for quick prototyping without
 * external services.
 *
 * Example:
 * ```typescript
 * const runner = new Runner({
 *   appName: 'my_app',
 *   agent: myAgent,
 *   sessionService: new InMemorySessionService(),
 * });
 *
 * for await (const event of runner.runAsync({
 *   userId: 'user1',
 *   sessionId: 'session1',
 *   newMessage: {parts: [{text: 'Hello'}]},
 * })) {
 *   console.log(event);
 * }
 * ```
 */
export class Runner {
  readonly [RUNNER_SIGNATURE_SYMBOL] = true;
  readonly appName: string;
  readonly agent: BaseAgent;
  readonly pluginManager: PluginManager;
  readonly artifactService?: BaseArtifactService;
  readonly sessionService: BaseSessionService;
  readonly memoryService?: BaseMemoryService;
  readonly credentialService?: BaseCredentialService;

  /**
   * Creates a new Runner instance.
   *
   * @param input The configuration for the runner.
   */
  constructor(input: RunnerConfig) {
    this.appName = input.appName;
    this.agent = input.agent;
    this.pluginManager = new PluginManager(input.plugins ?? []);
    this.artifactService = input.artifactService;
    this.sessionService = input.sessionService;
    this.memoryService = input.memoryService;
    this.credentialService = input.credentialService;
  }

  /**
   * Runs the agent with a new, ephemeral session.
   *
   * @param params.userId The user ID of the session.
   * @param params.newMessage A new message to append to the session.
   * @param params.stateDelta An optional state delta to apply to the session.
   * @param params.runConfig The run config for the agent.
   * @yields The Events generated by the agent.
   */
  async *runEphemeral(params: {
    userId: string;
    newMessage: Content;
    stateDelta?: Record<string, unknown>;
    runConfig?: RunConfig;
    customMetadata?: Record<string, unknown>;
  }): AsyncGenerator<Event, void, undefined> {
    const session = await this.sessionService.createSession({
      appName: this.appName,
      userId: params.userId,
    });
    const sessionId = session.id;

    try {
      yield* this.runAsync({
        userId: params.userId,
        sessionId,
        newMessage: params.newMessage,
        stateDelta: params.stateDelta,
        runConfig: params.runConfig,
        customMetadata: params.customMetadata,
      });
    } finally {
      await this.sessionService.deleteSession({
        appName: this.appName,
        userId: params.userId,
        sessionId,
      });
    }
  }

  /**
   * Runs the agent with the given message, and returns an async generator of
   * events.
   *
   * @param params.userId The user ID of the session.
   * @param params.sessionId The session ID of the session.
   * @param params.newMessage A new message to append to the session.
   * @param params.stateDelta An optional state delta to apply to the session.
   * @param params.runConfig The run config for the agent.
   * @yields The events generated by the agent.
   */
  // TODO - b/425992518: user, sessionId, and runConfig can be internalized.
  async *runAsync(params: {
    userId: string;
    sessionId: string;
    newMessage: Content;
    stateDelta?: Record<string, unknown>;
    runConfig?: RunConfig;
    abortSignal?: AbortSignal;
    customMetadata?: Record<string, unknown>;
  }): AsyncGenerator<Event, void, undefined> {
    const {userId, sessionId, stateDelta} = params;
    const runConfig = createRunConfig(params.runConfig);
    let newMessage = params.newMessage;

    // =========================================================================
    // Setup the session and invocation context
    // =========================================================================
    const span = tracer.startSpan('invocation');
    const ctx = trace.setSpan(context.active(), span);
    try {
      yield* runAsyncGeneratorWithOtelContext<Runner, Event>(
        ctx,
        this,
        async function* () {
          const session = await this.sessionService.getSession({
            appName: this.appName,
            userId,
            sessionId,
          });

          if (params.abortSignal?.aborted) {
            return;
          }

          if (!session) {
            if (!this.appName) {
              throw new Error(
                `Session lookup failed: appName must be provided in runner constructor`,
              );
            }
            throw new Error(`Session not found: ${sessionId}`);
          }

          if (runConfig.supportCfc && isLlmAgent(this.agent)) {
            const modelName = this.agent.canonicalModel.model;
            if (!isGemini2OrAbove(modelName)) {
              throw new Error(
                `CFC is not supported for model: ${
                  modelName
                } in agent: ${this.agent.name}`,
              );
            }

            if (!isBuiltInCodeExecutor(this.agent.codeExecutor)) {
              this.agent.codeExecutor = new BuiltInCodeExecutor();
            }
          }

          const invocationContext = new InvocationContext({
            artifactService: this.artifactService
              ? new ScopedArtifactService(
                  this.artifactService,
                  this.appName,
                  userId,
                  sessionId,
                )
              : undefined,
            sessionService: this.sessionService,
            memoryService: this.memoryService,
            credentialService: this.credentialService,
            invocationId: newInvocationContextId(),
            agent: this.agent,
            session,
            userContent: newMessage,
            runConfig,
            pluginManager: this.pluginManager,
            abortSignal: params.abortSignal,
          });

          // =========================================================================
          // Preprocess plugins on user message
          // =========================================================================
          const pluginUserMessage =
            await this.pluginManager.runOnUserMessageCallback({
              userMessage: newMessage,
              invocationContext,
            });

          if (params.abortSignal?.aborted) {
            return;
          }

          if (pluginUserMessage) {
            newMessage = pluginUserMessage as Content;
          }

          // =========================================================================
          // Append user message to session
          // =========================================================================
          if (newMessage) {
            if (!newMessage.parts?.length) {
              throw new Error('No parts in the newMessage.');
            }

            // Directly saves the artifacts (if applicable) in the user message and
            // replaces the artifact data with a file name placeholder.
            // TODO - b/425992518: fix Runner<>>ArtifactService leaky abstraction.
            if (runConfig.saveInputBlobsAsArtifacts) {
              await this.saveArtifacts(
                invocationContext.invocationId,
                session.userId,
                session.id,
                newMessage,
              );
              if (params.abortSignal?.aborted) {
                return;
              }
            }
            // Append the user message to the session with optional state delta.
            await this.sessionService.appendEvent({
              session,
              event: createEvent({
                invocationId: invocationContext.invocationId,
                author: 'user',
                actions: stateDelta
                  ? createEventActions({stateDelta})
                  : undefined,
                content: newMessage,
                customMetadata: params.customMetadata,
              }),
            });
            if (params.abortSignal?.aborted) {
              return;
            }
          }

          // =========================================================================
          // Determine which agent should handle the workflow resumption.
          // =========================================================================
          invocationContext.agent = this.determineAgentForResumption(
            session,
            this.agent,
          );

          // =========================================================================
          // Run the agent with the plugins (aka hooks to apply in the lifecycle)
          // =========================================================================
          if (newMessage) {
            // =========================================================================
            // Run the agent with the plugins (aka hooks to apply in the lifecycle)
            // =========================================================================
            // Step 1: Run the before_run callbacks to see if we should early exit.
            const beforeRunCallbackResponse =
              await this.pluginManager.runBeforeRunCallback({
                invocationContext,
              });
            if (params.abortSignal?.aborted) {
              return;
            }

            if (beforeRunCallbackResponse) {
              const earlyExitEvent = createEvent({
                invocationId: invocationContext.invocationId,
                author: 'model',
                content: beforeRunCallbackResponse,
              });
              // TODO: b/447446338 - In the future, do *not* save live call audio
              // content to session This is a feature in Python ADK
              await this.sessionService.appendEvent({
                session,
                event: earlyExitEvent,
              });
              if (params.abortSignal?.aborted) {
                return;
              }

              yield earlyExitEvent;
            } else {
              // Step 2: Otherwise continue with normal execution
              for await (const event of invocationContext.agent.runAsync(
                invocationContext,
              )) {
                if (params.abortSignal?.aborted) {
                  return;
                }

                if (!event.partial) {
                  await this.sessionService.appendEvent({session, event});
                }
                // Step 3: Run the on_event callbacks to optionally modify the event.
                const modifiedEvent =
                  await this.pluginManager.runOnEventCallback({
                    invocationContext,
                    event,
                  });
                if (params.abortSignal?.aborted) {
                  return;
                }

                if (modifiedEvent) {
                  yield modifiedEvent;
                } else {
                  yield event;
                }
              }
              // Step 4: Run the after_run callbacks to optionally modify the context.
              await this.pluginManager.runAfterRunCallback({invocationContext});
              if (params.abortSignal?.aborted) {
                return;
              }
            }
          }
        },
      );
    } finally {
      span.end();
      const toolsets = getAllToolsets(this.agent);
      await Promise.allSettled(toolsets.map((t) => t.close()));
    }
  }

  /**
   * Saves artifacts from the message parts and replaces the inline data with
   * a file name placeholder.
   *
   * @param invocationId The current invocation ID.
   * @param userId The user ID of the session.
   * @param sessionId The session ID of the session.
   * @param message The message containing parts to process.
   */
  private async saveArtifacts(
    invocationId: string,
    userId: string,
    sessionId: string,
    message: Content,
  ): Promise<void> {
    if (!this.artifactService || !message.parts?.length) {
      return;
    }

    for (let i = 0; i < message.parts.length; i++) {
      const part = message.parts[i];
      if (!part.inlineData) {
        continue;
      }
      const fileName = `artifact_${invocationId}_${i}`;
      // TODO - b/425992518: group appname, userId, sessionId as a key.
      await this.artifactService.saveArtifact({
        appName: this.appName,
        userId,
        sessionId,
        filename: fileName,
        artifact: part,
      });
      // TODO - b/425992518: potentially buggy if accidentally exposed to LLM.
      message.parts[i] = createPartFromText(
        `Uploaded file: ${fileName}. It is saved into artifacts`,
      );
    }
  }

  /**
   * Determines which agent in the hierarchy should run when continuing or resuming
   * an existing session.
   *
   * This method implements a three-case routing strategy:
   *
   * Case 1 (Function Response Matching):
   *   If the last event in the session is a user `FunctionResponse` corresponding
   *   to a previous `FunctionCall`, execution must route back to the specific
   *   agent that authored the original function call so it can process the tool
   *   output (`findEventByLastFunctionResponseId`). If the authoring agent is not
   *   found in the current tree, it falls back to `rootAgent`.
   *
   * Case 2 (Transferable LLM Agent Scan):
   *   Otherwise, the runner scans backwards through historical events (`session.events`)
   *   to find the last non-user agent that emitted a message. When an agent author
   *   is resolved, `isRoutableLlmAgent` checks whether the agent is transferable across
   *   the tree. To be transferable, an agent must be an `LlmAgent` (`!isLlmAgent` agents
   *   or non-LLM workflow agents cannot be resumed directly as conversational endpoints)
   *   and neither the agent nor any of its ancestors up the chain may have
   *   `disallowTransferToParent` set to `true`. If an agent is non-transferable, the
   *   runner skips it and continues scanning backwards.
   *
   * Case 3 (Root Agent Fallback):
   *   If no matching function response is found and no historical event authored by a
   *   transferable `LlmAgent` is resolved, routing defaults to `rootAgent`.
   *
   * @param session The active session containing historical events.
   * @param rootAgent The root agent of the execution hierarchy.
   * @returns The resolved `BaseAgent` instance to continue session execution.
   */
  // TODO - b/425992518: This is where LRO integration should happen.
  // Needs clean up before we can generalize it.
  private determineAgentForResumption(
    session: Session,
    rootAgent: BaseAgent,
  ): BaseAgent {
    // simplicity: Build agent lookup map once per resumption call (O(M)). Upgrade to memoization/cache on Runner if tree size M becomes extremely large and static.
    const agentMap = buildAgentLookupMap(rootAgent);

    // =========================================================================
    // Case 1: If the last event is a function response, this returns the
    // agent that made the original function call.
    // =========================================================================
    const event = findEventByLastFunctionResponseId(session.events);
    if (event && event.author) {
      const target = agentMap.get(event.author) || rootAgent;
      logger.debug(
        `Resuming session from function response with agent: ${target.name}`,
      );
      return target;
    }

    // =========================================================================
    // Case 2: Otherwise, find the last agent that emitted a message and is
    // transferable across the agent tree.
    // =========================================================================
    for (let i = session.events.length - 1; i >= 0; i--) {
      const event = session.events[i];
      if (event.author === 'user' || !event.author) {
        continue;
      }

      if (event.author === rootAgent.name) {
        logger.debug(`Resuming session with root agent: ${rootAgent.name}`);
        return rootAgent;
      }

      const agent = agentMap.get(event.author);
      if (!agent) {
        logger.warn(
          `Event from an unknown agent: ${event.author}, event id: ${event.id}`,
        );
        continue;
      }
      if (this.isRoutableLlmAgent(agent)) {
        logger.debug(`Resuming session with transferable agent: ${agent.name}`);
        return agent;
      }
    }
    // =========================================================================
    // Case 3: default to root agent.
    // =========================================================================
    logger.debug(
      `Resuming session defaulting to root agent: ${rootAgent.name}`,
    );
    return rootAgent;
  }

  /**
   * Determines whether an agent is capable of being routed to and transferred across
   * the agent tree during session resumption (Case 2 of `determineAgentForResumption`).
   *
   * An agent is considered routable/transferable if both of the following hold:
   *  - It is an instance of `LlmAgent` (`isLlmAgent(agent) === true`). Non-LLM agents
   *    (e.g., specialized workflow or static agents) cannot be resumed directly as the
   *    active LLM endpoint.
   *  - It is permitted to transfer control up to its parent hierarchy. Specifically,
   *    neither the agent itself nor any of its ancestor agents up the `parentAgent`
   *    chain may have `disallowTransferToParent === true`. If any ancestor forbids
   *    transferring to parent, the sub-agent is encapsulated and cannot be directly
   *    resumed from outside its branch during global session scanning.
   *
   * @param agentToRun The agent to evaluate for transferability.
   * @returns `true` if the agent can be resumed and transferred to, `false` otherwise.
   */
  private isRoutableLlmAgent(agentToRun: BaseAgent): boolean {
    let agent: BaseAgent | undefined = agentToRun;
    while (agent) {
      if (!isLlmAgent(agent)) {
        return false;
      }
      if (agent.disallowTransferToParent) {
        return false;
      }
      agent = agent.parentAgent;
    }
    return true;
  }
  // TODO - b/425992518: Implement runLive and related methods.
}

/**
 * It iterates through the events in reverse order, and returns the event
 * containing a function call with a functionCall.id matching the
 * functionResponse.id from the last event in the session.
 */
// TODO - b/425992518: a hack that used event log as transaction log. Fix.
function findEventByLastFunctionResponseId(events: Event[]): Event | null {
  if (!events.length) {
    return null;
  }

  const lastEvent = events[events.length - 1];
  const functionCallId = lastEvent.content?.parts?.find(
    (part) => part.functionResponse,
  )?.functionResponse?.id;
  if (!functionCallId) {
    return null;
  }

  // TODO - b/425992518: inefficient search, fix.
  for (let i = events.length - 2; i >= 0; i--) {
    const event = events[i];
    // Looking for the system long running request euc function call.
    const functionCalls = getFunctionCalls(event);
    if (!functionCalls) {
      continue;
    }

    for (const functionCall of functionCalls) {
      if (functionCall.id === functionCallId) {
        return event;
      }
    }
  }
  return null;
}

function getAllToolsets(agent: BaseAgent): BaseToolset[] {
  const toolsets: BaseToolset[] = [];
  const visited = new Set<BaseAgent>();

  function traverse(curr: BaseAgent) {
    if (visited.has(curr)) return;
    visited.add(curr);

    if (isLlmAgent(curr)) {
      for (const tool of curr.tools) {
        if (isBaseToolset(tool)) {
          toolsets.push(tool);
        }
      }
    }

    for (const sub of curr.subAgents) {
      traverse(sub);
    }
  }

  traverse(agent);
  return toolsets;
}

/**
 * Builds a map of agent names to agent instances across the hierarchy
 * starting from the given root agent and visiting all descendants using
 * preorder depth-first traversal (matching findAgent/findSubAgent order).
 */
function buildAgentLookupMap(rootAgent: BaseAgent): Map<string, BaseAgent> {
  const map = new Map<string, BaseAgent>();
  const visited = new Set<BaseAgent>();

  function traverse(curr: BaseAgent) {
    if (visited.has(curr)) return;
    visited.add(curr);

    if (!map.has(curr.name)) {
      map.set(curr.name, curr);
    }

    for (const sub of curr.subAgents) {
      traverse(sub);
    }
  }

  traverse(rootAgent);
  return map;
}
