/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {Client} from '@google-cloud/vertexai';
import {
  AgentEngineSandboxCodeExecutor,
  CODE_EXECUTION_RESPONSE_PROCESSOR,
  LlmAgent,
} from '@google/adk';
import {FinishReason, Outcome} from '@google/genai';
import {describe, expect, it, vi} from 'vitest';
import {
  collectEvents,
  createRunner,
  GeminiWithMockResponses,
  RawGenerateContentResponse,
} from '../test_case_utils.js';

/**
 * Builds a fresh set of recorded responses for one test.
 *
 * The response processor truncates `content.parts` in place and
 * `GeminiWithMockResponses` hands out the same `Candidate` objects it is
 * constructed with, so a fixture shared between tests would be rewritten by
 * whichever test runs first.
 */
function mockResponses(): RawGenerateContentResponse[] {
  return [
    {
      candidates: [
        {
          content: {
            parts: [
              {
                text: 'Here is the code to print hello:\n```python\nprint("hello")\n```',
              },
            ],
            role: 'model',
          },
          finishReason: FinishReason.STOP,
        },
      ],
    },
    {
      candidates: [
        {
          content: {
            parts: [{text: 'Execution was successful.'}],
            role: 'model',
          },
          finishReason: FinishReason.STOP,
        },
      ],
    },
  ];
}

/**
 * Builds a stub Vertex AI client for one test, returning it already typed as a
 * `Client` alongside the code-execution spy so callers need no cast.
 */
function createMockClient() {
  const executeCodeInternal = vi.fn().mockResolvedValue({
    outputs: [
      {
        mimeType: 'application/json',
        data: Buffer.from(
          JSON.stringify({msg_out: 'hello', msg_err: ''}),
        ).toString('base64'),
      },
    ],
  });

  const client = {
    agentEnginesInternal: {
      createInternal: vi.fn().mockResolvedValue({
        name: 'operations/create-engine-op',
        done: true,
        response: {
          name: 'projects/test-project/locations/us-central1/reasoningEngines/123',
        },
      }),
      sandboxes: {
        getInternal: vi.fn().mockResolvedValue({
          state: 'STATE_RUNNING',
        }),
        createInternal: vi.fn().mockResolvedValue({
          name: 'operations/create-sandbox-op',
          done: true,
          response: {
            name: 'projects/test-project/locations/us-central1/reasoningEngines/123/sandboxEnvironments/456',
          },
        }),
        executeCodeInternal,
      },
    },
  } as unknown as Client;

  return {client, executeCodeInternal};
}

describe('Agent with AgentEngineSandboxCodeExecutor', () => {
  it('executes code generated by the agent', async () => {
    const {client} = createMockClient();

    const executor = new AgentEngineSandboxCodeExecutor({
      projectId: 'test-project',
      client,
    });

    const model = new GeminiWithMockResponses(mockResponses());
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
      responseProcessors: [CODE_EXECUTION_RESPONSE_PROCESSOR],
    });

    const {run} = await createRunner(agent);

    const events = await collectEvents(run, 'Print hello');

    // We expect events for:
    // 1. User message (handled by runner)
    // 2. Model response with code
    // 3. Execution result
    // 4. Final model response

    expect(events.length).toBeGreaterThanOrEqual(3);

    // Check if we got a code execution result event
    const hasExecutionResult = events.some(
      (e) =>
        e.content?.parts?.some((p) => p.text && p.text.includes('hello')) ||
        (e.content?.parts?.[0]?.inlineData?.data &&
          Buffer.from(e.content.parts[0].inlineData.data, 'base64')
            .toString('utf-8')
            .includes('hello')),
    );

    expect(hasExecutionResult).toBe(true);
  });

  it('executes code with no explicit responseProcessors', async () => {
    const {client, executeCodeInternal} = createMockClient();

    const executor = new AgentEngineSandboxCodeExecutor({
      projectId: 'test-project',
      client,
    });

    const model = new GeminiWithMockResponses(mockResponses());
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
    });

    const {run} = await createRunner(agent);

    const events = await collectEvents(run, 'Print hello');

    expect(executeCodeInternal).toHaveBeenCalledTimes(1);

    const resultParts = events.flatMap(
      (e) => e.content?.parts?.filter((p) => p.codeExecutionResult) ?? [],
    );
    expect(resultParts).toHaveLength(1);
    expect(resultParts[0].codeExecutionResult?.outcome).toBe(
      Outcome.OUTCOME_OK,
    );
    expect(resultParts[0].text).toContain('hello');

    expect(events.at(-1)?.content?.parts?.[0]?.text).toBe(
      'Execution was successful.',
    );
  });
});
