/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  type Event,
  GkeCodeExecutor,
  LlmAgent,
  type SandboxClient,
} from '@google/adk';
import {responseProcessor} from '@google/adk/agents/processors/code_execution_request_processor.js';
import {FinishReason} from '@google/genai';
import {describe, expect, it, vi} from 'vitest';
import {
  createRunner,
  GeminiWithMockResponses,
  RawGenerateContentResponse,
} from '../test_case_utils.js';

/** Sandbox output chosen so it cannot appear in the prompt or the model text. */
const SANDBOX_STDOUT = 'sandbox-stdout-42';

describe('Agent with GkeCodeExecutor sandbox mode', () => {
  it('executes code generated by the agent through the injected sandbox', async () => {
    const mockResponses: RawGenerateContentResponse[] = [
      {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: 'Here is the code to print hello:\n```python\nprint("hello")\n```',
                },
              ],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
      {
        candidates: [
          {
            content: {
              parts: [{text: 'Execution was successful.'}],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
    ];

    // A mock Agent Sandbox client: write the script, run it, return stdout.
    // The stdout is deliberately unlike the prompt and the model text, so the
    // assertion below can only pass if it came from the sandbox.
    const sandbox: SandboxClient = {
      write: vi.fn().mockResolvedValue(undefined),
      run: vi.fn().mockResolvedValue({stdout: SANDBOX_STDOUT, stderr: ''}),
      close: vi.fn().mockResolvedValue(undefined),
    };
    const sandboxClientFactory = vi.fn(() => sandbox);

    const executor = new GkeCodeExecutor({
      namespace: 'agents',
      sandboxClientFactory,
    });

    const model = new GeminiWithMockResponses(mockResponses);
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
      responseProcessors: [responseProcessor],
    });

    const {run} = await createRunner(agent);

    const events: Event[] = [];
    for await (const event of run('Print hello')) {
      events.push(event);
    }

    // The code block was extracted from the model response and reached the
    // sandbox verbatim. (The sandbox call sequence itself is unit-tested.)
    expect(sandbox.write).toHaveBeenCalledWith('script.py', 'print("hello")');

    // A code-execution result part carrying the sandbox stdout flowed through.
    const executionResult = events
      .flatMap((e) => e.content?.parts ?? [])
      .find((p) => p.codeExecutionResult);

    expect(executionResult?.text).toContain(SANDBOX_STDOUT);
  });
});
