/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  AgentSandboxClient,
  GkeCodeExecutor,
  LlmAgent,
  type SandboxClient,
  type SandboxClientOptions,
} from '@google/adk';
import {responseProcessor} from '@google/adk/agents/processors/code_execution_request_processor.js';
import {FinishReason} from '@google/genai';
import {KubeConfig} from '@kubernetes/client-node';
import {describe, expect, it, vi} from 'vitest';
import {
  createRunner,
  GeminiWithMockResponses,
  RawGenerateContentResponse,
} from '../test_case_utils.js';

/** Two-turn model script: emit a Python block, then a closing message. */
function codePrintingResponses(): RawGenerateContentResponse[] {
  return [
    {
      candidates: [
        {
          content: {
            parts: [
              {
                text: 'Here is the code to print hello:\n```python\nprint("hello")\n```',
              },
            ],
            role: 'model',
          },
          finishReason: FinishReason.STOP,
        },
      ],
    },
    {
      candidates: [
        {
          content: {
            parts: [{text: 'Execution was successful.'}],
            role: 'model',
          },
          finishReason: FinishReason.STOP,
        },
      ],
    },
  ];
}

describe('Agent with GkeCodeExecutor sandbox mode', () => {
  it('executes code generated by the agent through the injected sandbox', async () => {
    const mockResponses: RawGenerateContentResponse[] = [
      {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: 'Here is the code to print hello:\n```python\nprint("hello")\n```',
                },
              ],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
      {
        candidates: [
          {
            content: {
              parts: [{text: 'Execution was successful.'}],
              role: 'model',
            },
            finishReason: FinishReason.STOP,
          },
        ],
      },
    ];

    // A mock Agent Sandbox client: write the script, run it, return stdout.
    const sandbox: SandboxClient = {
      write: vi.fn().mockResolvedValue(undefined),
      run: vi.fn().mockResolvedValue({stdout: 'hello', stderr: ''}),
      close: vi.fn().mockResolvedValue(undefined),
    };
    const sandboxClientFactory = vi.fn(
      (_options: SandboxClientOptions) => sandbox,
    );

    const executor = new GkeCodeExecutor({
      executorType: 'sandbox',
      namespace: 'agents',
      sandboxClientFactory,
    });

    const model = new GeminiWithMockResponses(mockResponses);
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
      responseProcessors: [responseProcessor],
    });

    const {run} = await createRunner(agent);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const events: any[] = [];
    for await (const event of run('Print hello')) {
      events.push(event);
    }

    // Events for: model response with code, execution result, final response.
    expect(events.length).toBeGreaterThanOrEqual(3);

    // The sandbox client received the script and the run command.
    expect(sandboxClientFactory).toHaveBeenCalledTimes(1);
    expect(sandbox.write).toHaveBeenCalledWith('script.py', 'print("hello")');
    expect(sandbox.run).toHaveBeenCalledWith('python3 script.py');
    expect(sandbox.close).toHaveBeenCalledTimes(1);

    // A code-execution result event carrying the sandbox stdout flowed through.
    const hasExecutionResult = events.some(
      (e) =>
        e.content?.parts?.some(
          (p: {text?: string}) => p.text && p.text.includes('hello'),
        ) ||
        (e.content?.parts?.[0]?.inlineData?.data &&
          Buffer.from(e.content.parts[0].inlineData.data, 'base64')
            .toString('utf-8')
            .includes('hello')),
    );

    expect(hasExecutionResult).toBe(true);
  });

  it('runs end-to-end through the real AgentSandboxClient', async () => {
    // Only the two true external boundaries are faked: the Kubernetes API and
    // the router HTTP transport. The AgentSandboxClient, GkeCodeExecutor, and
    // agent pipeline are exercised for real.
    const routerCalls: string[] = [];
    const fetchFn = vi.fn(async (url: string) => {
      routerCalls.push(url);
      return {
        status: 200,
        ok: true,
        type: 'basic',
        json: async () => ({stdout: 'hello', stderr: '', exit_code: 0}),
      } as unknown as Response;
    });
    const api = {
      getNamespacedCustomObject: vi.fn(({plural}: {plural: string}) => {
        if (plural === 'sandboxtemplates') {
          return Promise.resolve({
            spec: {podTemplate: {spec: {containers: [{name: 'python'}]}}},
          });
        }
        if (plural === 'sandboxes') {
          return Promise.resolve({
            metadata: {name: 'adk-sandbox-e2e'},
            status: {
              conditions: [{type: 'Ready', status: 'True'}],
              podIPs: ['10.0.0.7'],
            },
          });
        }
        return Promise.resolve({status: {addresses: [{value: '10.0.0.1'}]}});
      }),
      createNamespacedCustomObject: vi.fn(() =>
        Promise.resolve({metadata: {name: 'adk-sandbox-e2e'}}),
      ),
      deleteNamespacedCustomObject: vi.fn(() => Promise.resolve({})),
    };
    const kubeConfig = {
      makeApiClient: () => api,
    } as unknown as KubeConfig;

    const sandboxClientFactory = vi.fn(
      (options: SandboxClientOptions) =>
        new AgentSandboxClient({
          ...options,
          kubeConfig,
          fetchFn: fetchFn as unknown as typeof fetch,
        }),
    );

    const executor = new GkeCodeExecutor({
      executorType: 'sandbox',
      namespace: 'agent-sandbox',
      sandboxTemplate: 'python-sandbox-template',
      sandboxGatewayName: 'external-http-gateway',
      sandboxClientFactory,
    });

    const model = new GeminiWithMockResponses(codePrintingResponses());
    const agent = new LlmAgent({
      model,
      name: 'coderAgent',
      description: 'An agent that writes and runs code',
      instruction: 'Write code to solve the user request.',
      codeExecutor: executor,
      responseProcessors: [responseProcessor],
    });

    const {run} = await createRunner(agent);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const events: any[] = [];
    for await (const event of run('Print hello')) {
      events.push(event);
    }

    // The real client provisioned the sandbox and called the router endpoints.
    expect(api.createNamespacedCustomObject).toHaveBeenCalledTimes(1);
    expect(routerCalls).toEqual([
      'http://10.0.0.1/upload',
      'http://10.0.0.1/execute',
    ]);
    expect(api.deleteNamespacedCustomObject).toHaveBeenCalledTimes(1);

    const hasExecutionResult = events.some((e) =>
      e.content?.parts?.some(
        (p: {text?: string}) => p.text && p.text.includes('hello'),
      ),
    );
    expect(hasExecutionResult).toBe(true);
  });
});
