name: auto-assignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run auto-assignment script
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          script: |
            const path = require('path');
            const { pathToFileURL } = require('url');

            const filePath = path.resolve('./scripts/auto-assignment.mjs');
            const fileUrl = pathToFileURL(filePath).href;

            const importedModule = await import(fileUrl);
            await importedModule.default({ github, context });
